# Machine Problems Challenge 

# Level 1

### 1.1. Swap rows

Using array indexing, swap rows 1 and 2 of the array: 

```
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
```

Output
```
array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])
```

In [1]:
import numpy as np
a=np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8]])
a[[0,2,1]]

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

### 1.2. Swap columns

Using array indexing, swap columns 1 and 2 of the array: 

```
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
```

Output
```
array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])
```

In [2]:
a[:,[0,2,1]]

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

### 1.3 Normalize an array
Define a function `normalize` that takes in an array `input_array` and converts all of its elements to its normalized form by the formula
$ normed  = \frac{element - min}{max - min}$

that is, array minimum is set to have a value 0, array maximum has value 1, and all other elements are linearly scaled in between.

Test it for array

```
array([[86, 80, 95],
       [96, 91, 70],
       [92, 82, 81]])
```

In [3]:
b=np.array([[86, 80, 95],[96, 91, 70], [92, 82, 81]])

def normalize(input_array):
    return (input_array-np.min(input_array))/(np.max(input_array)-np.min(input_array))

normalize(b)

array([[0.61538462, 0.38461538, 0.96153846],
       [1.        , 0.80769231, 0.        ],
       [0.84615385, 0.46153846, 0.42307692]])

# Level 2

### 2.1. Alphabet index cipher
Define a function `alphabet_index_cipher` that replaces all alphabet characters in an input string with its index position in the alphabet.

Fix all characters to lowercase and set spaces = 0

*Desired Output*:
```
this_string = "eskwelabs the best"

output = '51911235121219020850251920'
```




In [4]:
def alphabet_index_cipher(mystring):
    alphabet = [' ', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j','k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
    output=''
    for i in mystring:
        output += str(alphabet.index(i))
    return output

alphabet_index_cipher("eskwelabs the best")

'51911235121219020850251920'

### 2.2 Caesar cipher
Named after Julius Caesar, the Caesar cipher is one of the earliest known and simplest ciphers and was used to communicate orders with his generals. It is a type of substitution cipher in which each letter in the plaintext is 'shifted' a certain number of places down the alphabet. For example, with a shift of 1, A would be replaced by B, B would become C, and so on. 

Define a function `caesar_cipher` that takes in the input string and a nonnegative shift value `shift` and returns the encoded Caesar cipher of the string

*Desired Output*:
```
plaintext:  defend the east wall of the castle
ciphertext with shift =1: efgfoe uif fbtu xbmm pg uif dbtumf
```

In [5]:
def caesar_cipher(mystring, shift): 
    result = "" 
  
    # traverse text 
    for i in range(len(mystring)): 
        char = mystring[i] 
        
        if char==' ':
            result+=' '
        else:
            result += chr((ord(char) + shift - 97) % 26 + 97) 
        
    return result 
  
mystring = "defend the east wall of the castle"
shift = 1

print("Text  : " + mystring) 
print("Shift : " + str(shift)) 
print("Cipher: " + caesar_cipher(mystring,shift)) 

Text  : defend the east wall of the castle
Shift : 1
Cipher: efgfoe uif fbtu xbmm pg uif dbtumf


# Level 3

### 3.1 Perfect numbers
A perfect number is any positive integer > 1 which is equal to the sum of its proper divisors (all its divisors except for itself).

Use loops and/or list comprehensions to generate the list of all perfect numbers less than 10000.

Hint: 
1. It might be helpful to first define a function / write a list comprehension to find the factors of a number
2. The `set` built-in function, which gets unique elements in a list, would be useful


In [6]:
numbers = range(2,10000)

import math

for num in numbers:
    ans,div=1,2
    while (div*div<num):
        if(num % div == 0):
            ans+=div+num//div
        div+=1
    if (ans == num): print(num, end=' ')    

6 28 496 8128 

### 3.2 Erathosthenes sieve

The following is a description of Erathosthenes (276-194 BCE) algorithm to find all the prime numbers less than or equal to a given integer n:

Watch: https://www.youtube.com/watch?v=9m2cdWorIq8

Find all prime numbers from 1 to 500. Implement this using a combination of for/while loops and list comprehension. 

Hint: For those attempting the pure list comprehension implementation, the `set` built-in function, which gets unique elements in a list, would be useful

In [7]:
numbers = range(2,500)

prime = [2]
for i in numbers:
    count = 0
    for j in prime:
        if i%j == 0:
            break
        else:
            count += 1
    if count==len(prime):
        prime.append(i)
print(prime)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499]
